import React, { useRef, useLayoutEffect } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { Network, Mic2 } from 'lucide-react';

gsap.registerPlugin(ScrollTrigger);

export function SystemPitch() {
  const sectionRef = useRef<HTMLElement>(null);
  
  useLayoutEffect(() => {
    let ctx = gsap.context(() => {
      gsap.fromTo('.pitch-element',
        { y: 40, opacity: 0 },
        {
          y: 0,
          opacity: 1,
          duration: 0.8,
          stagger: 0.2,
          ease: 'power3.out',
          scrollTrigger: {
            trigger: sectionRef.current,
            start: 'top 70%',
          }
        }
      );
    }, sectionRef);
    return () => ctx.revert();
  }, []);

  return (
    <section id="system-pitch-section" ref={sectionRef} className="py-24 bg-[#020202] border-t border-white/5 relative overflow-hidden">
      <div className="max-w-[1600px] mx-auto px-4 lg:px-6 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 lg:gap-24">
          
          {/* Left: Text Content */}
          <div className="flex flex-col justify-center">
            <div className="pitch-element inline-flex items-center gap-2 mb-6">
              <span className="text-[#84CC16] text-sm font-bold tracking-[3px] uppercase">
                COGNITIVE ARCHITECTURE
              </span>
            </div>
            
            <h2 className="pitch-element text-4xl lg:text-5xl font-bold text-white mb-8 uppercase tracking-tight leading-[1.1]">
              The Evolution of Cognitive Communication Systems
            </h2>
            
            <p className="pitch-element text-white/60 text-lg leading-relaxed mb-8">
              In multi-domain operations, the sheer volume of data generated by sensors, drones, and ground units overwhelms traditional communication systems. True spectrum dominance now requires cognitive intervention. Our Defence Deeptech architecture acts as the brain behind the communication network—utilizing AI and Big Data to filter out noise, translate tactical voice commands in real-time, and securely route highly synthesized intelligence to command centers before human operators even perceive a threat.
            </p>
          </div>

          {/* Right: Cards */}
          <div className="flex flex-col justify-center gap-6">
            <div className="pitch-element bg-[#0a0a0a] border border-white/10 p-8 rounded-xl hover:border-[#84CC16]/30 transition-colors group relative overflow-hidden">
              <div className="absolute inset-0 bg-gradient-to-r from-[#84CC16]/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
              <Network className="w-8 h-8 text-[#84CC16] mb-6" />
              <h3 className="text-xl font-bold text-white mb-3 uppercase tracking-wide">
                Semantic Data Routing
              </h3>
              <p className="text-white/60 leading-relaxed">
                AI algorithms automatically prioritize and route mission-critical communications across congested bandwidths.
              </p>
            </div>

            <div className="pitch-element bg-[#0a0a0a] border border-white/10 p-8 rounded-xl hover:border-[#84CC16]/30 transition-colors group relative overflow-hidden">
              <div className="absolute inset-0 bg-gradient-to-r from-[#84CC16]/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
              <Mic2 className="w-8 h-8 text-[#84CC16] mb-6" />
              <h3 className="text-xl font-bold text-white mb-3 uppercase tracking-wide">
                Voice-to-Action Protocol
              </h3>
              <p className="text-white/60 leading-relaxed">
                Natural Language Processing (NLP) translates encrypted voice comms into actionable, machine-readable C2 telemetry.
              </p>
            </div>
          </div>
          
        </div>
      </div>
    </section>
  );
}
